// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyevaipvyalmruxlwexz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZXZhaXB2eWFsbXJ1eGx3ZXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTkxNTAsImV4cCI6MjA3MzQzNTE1MH0.MDCduPIZCtSnaNV0cdLf9nhwScKa37yk8HLSGDbJyXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});